# Generated by Django 2.0.4 on 2018-05-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MillenialPet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Sin descripcion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='num_paquete',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='ImgPlanes', verbose_name='Imagen'),
        ),
    ]
